upstreams:
  init:
    strategy: failOnError
  groups:
    default:
      - 8.8.8.8
      - 1.1.1.1
      - 9.9.9.9

customDNS:
  customTTL: 1h
  filterUnmappedTypes: false
  mapping:
    innokentii-kozlov.com: 192.168.40.118
    dell-optiplex-3000.innokentii-kozlov.com: 192.168.40.118
    raspberrypi-5.innokentii-kozlov.com: 192.168.40.174
    git.innokentii-kozlov.com: 192.168.40.174

blocking:
  denylists:
    ads:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - http://sysctl.org/cameleon/hosts
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    special:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
  clientGroupsBlock:
    default:
      - ads
      - special

prometheus:
  enable: true
  path: /metrics

ports:
  dns:
    - 53
  http: 4000
