{
 "title": "Authentik",
 "description": "Grafana Dashboard for Prometheus metrics exposed by authentik.",
 "tags": [
  "authentik",
  "sso"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "authentik_outpost_connection" } },
   {
    "name": "outpost_proxy",
    "label": "Outposts (Proxy)",
    "query": {
     "query": "authentik_outpost_info{outpost_type=\"proxy\"}"
    }
   },
   {
    "name": "outpost_ldap",
    "label": "Outposts (LDAP)",
    "query": {
     "query": "authentik_outpost_info{outpost_type=\"ldap\"}"
    }
   },
   {
    "name": "outpost_radius",
    "label": "Outposts (Radius)",
    "query": {
     "query": "authentik_outpost_info{outpost_type=\"radius\"}"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "authentik Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FlowPlanner time by flow",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (flow_slug) (rate(authentik_flows_plan_time_sum{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{ stage_type }}"
    }
   ]
  },
  {
   "title": "Task status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(authentik_tasks_errors_total{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(authentik_tasks_total{namespace=~\"$namespace\"})",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": {
    "content": "\n\n<img src=\"https://goauthentik.io/img/icon_top_brand.svg\">"
   }
  },
  {
   "title": "Connected Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(authentik_admin_workers{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Cached policies",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(authentik_policies_cached{namespace=~\"$namespace\"})",
     "legendFormat": "Cached policies"
    }
   ]
  },
  {
   "title": "Connected Outposts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(authentik_outposts_connected{namespace=~\"$namespace\"}) by (outpost)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PolicyEngine Execution time by binding type (Top 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, avg by(binding_target_type, mode) (rate(authentik_policies_execution_time_bucket{namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "{{ binding_target_type }} {{ mode }}"
    }
   ]
  },
  {
   "title": "System task duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (actor_name) (rate(authentik_tasks_duration_milliseconds_bucket{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{ task_name }}"
    }
   ]
  },
  {
   "title": "PolicyEngine Execution time by binding target (Top 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, avg by(object_type, mode) (rate(authentik_policies_execution_time_sum{namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "{{ object_type }} {{ mode }}"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 21 },
   "targets": [
    {
     "expr": "sum(authentik_tasks_queued{namespace=~\"$namespace\"})",
     "legendFormat": "{{ task_name }}"
    }
   ]
  },
  {
   "title": "authentik Proxy Outpost $outpost_proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "repeat": "outpost_proxy",
   "collapsed": true,
   "panels": [
    {
     "title": "Outpost requests (per 5 minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
     "targets": [
      {
       "expr": "sum(rate(authentik_outpost_proxy_request_duration_seconds_count{namespace=~\"$namespace\", outpost_name=\"$outpost_proxy\"}[$__rate_interval])) by (host)",
       "legendFormat": "{{ host }} {{ path }}"
      }
     ]
    },
    {
     "title": "Outpost upstream requests (per 5 minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
     "targets": [
      {
       "expr": "sum(rate(authentik_outpost_proxy_upstream_response_duration_seconds_count{namespace=~\"$namespace\", outpost_name=\"$outpost_proxy\"}[$__rate_interval])) by (host)",
       "legendFormat": "{{ host }}"
      }
     ]
    }
   ]
  },
  {
   "title": "authentik LDAP Outpost $outpost_ldap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "repeat": "outpost_ldap",
   "collapsed": true,
   "panels": [
    {
     "title": "LDAP Requests (per 5 minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
     "targets": [
      {
       "expr": "avg by (dn) (rate(authentik_outpost_ldap_requests_bucket{namespace=~\"$namespace\", outpost_name=\"$outpost_ldap\"}[5m]))",
       "legendFormat": "{{ dn }}"
      }
     ]
    },
    {
     "title": "LDAP Rejected Requests (per 5 minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
     "targets": [
      {
       "expr": "avg by (reason) (rate(authentik_outpost_ldap_requests_rejected{namespace=~\"$namespace\", outpost_name=\"$outpost_ldap\"}[5m]))",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "FlowExecutor Timings",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 136 },
     "targets": [
      {
       "expr": "avg by (flow) (rate(authentik_outpost_flow_timing_get_bucket{namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "{{ flow }} GET"
      },
      {
       "expr": "avg by (flow) (rate(authentik_outpost_flow_timing_post_bucket{namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "{{ flow }} POST"
      }
     ]
    },
    {
     "title": "LDAP Requests by type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 136 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "group by (type) (authentik_outpost_ldap_requests_sum)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "LDAP Rejected Requests by reason",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 136 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "group by (reason) (authentik_outpost_ldap_requests_rejected)",
       "legendFormat": "{{ reason }}"
      }
     ]
    }
   ]
  },
  {
   "title": "authentik Radius Outpost $outpost_radius",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "repeat": "outpost_radius",
   "collapsed": true,
   "panels": [
    {
     "title": "Radius request duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
     "targets": [
      {
       "expr": "authentik_outpost_radius_request_duration_seconds_count{namespace=~\"$namespace\", outpost_name=~\"$outpost_radius\"}",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "FlowExecutor Timings",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
     "targets": [
      {
       "expr": "avg by (flow) (rate(authentik_outpost_flow_timing_get_seconds_count{namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{ flow }} GET"
      },
      {
       "expr": "avg by (flow) (rate(authentik_outpost_flow_timing_post_seconds_bucket{namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{ flow }} POST"
      }
     ]
    }
   ]
  }
 ]
}