---
downloads_dir: "{{ workspace }}/downloads"

ssh:
  dir: "{{ workspace }}/ssh"
  key_name: id_rsa

cloud_init:
  work_dir: "{{ workspace }}/cloud-init"
  instance_id: "{{ hostvars['raspberry-pi-5']['fqdn'] }}"
  hostname: "{{ hostvars['raspberry-pi-5']['fqdn'] }}"
  username: "{{ hostvars['raspberry-pi-5']['ansible_user'] }}"
  password_hash: >-
    {{
      lookup('ansible.builtin.password', workspace ~ '/secret')
      | password_hash('sha512')
    }}
  network_interface: eth0
  ip_addresses:
    - "{{ hostvars['raspberry-pi-5']['ansible_host'] }}/24"
  gateway: 192.168.0.1
  nameservers:
    - 1.1.1.1
    - 8.8.8.8

rpi_os:
  base_url: https://downloads.raspberrypi.com
  release_date: '2025-12-04'
  variant: lite
  arch: arm64
  os_name: raspios
  os_version: trixie
  file_extension: img.xz
  image_compressed: >-
    {{ rpi_os.os_name }}-{{ rpi_os.os_version }}-{{ rpi_os.arch }}-
    {{ rpi_os.variant }}.{{ rpi_os.file_extension }}
  image: >-
    {{ rpi_os.os_name }}-{{ rpi_os.os_version }}-{{ rpi_os.arch }}-
    {{ rpi_os.variant }}.img
  download_url: >-
    {{ rpi_os.base_url }}/{{ rpi_os.os_name }}_{{ rpi_os.variant }}_
    {{ rpi_os.arch }}/images/{{ rpi_os.os_name }}_{{ rpi_os.variant }}_
    {{ rpi_os.arch }}-{{ rpi_os.release_date }}/
    {{ rpi_os.release_date }}-{{ rpi_os.image_compressed }}
  bootfs_partition_label: "W95 FAT32"
  sector_size: 512

mount:
  mount_point: "{{ workspace }}/mnt"
  nvme_usb_mount: /dev/sda
