[[registry]]
location = "docker.io"

[[registry.mirror]]
location = "zot.innokentii-kozlov.com/docker-images"

[[registry]]
location = "ghcr.io"

[[registry.mirror]]
location = "zot.innokentii-kozlov.com/ghcr-images"

[[registry]]
location = "quay.io"

[[registry.mirror]]
location = "zot.innokentii-kozlov.com/quay-images"

[[registry]]
location = "gcr.io"

[[registry.mirror]]
location = "zot.innokentii-kozlov.com/gcr-images"

[[registry]]
location = "data.forgejo.org"

[[registry.mirror]]
location = "zot.innokentii-kozlov.com/forgejo-images"

[[registry]]
location = "codeberg.org"

[[registry.mirror]]
location = "zot.innokentii-kozlov.com/codeberg-images"
