---
- name: Ensure SSH key directory exists
  ansible.builtin.file:
    path: "{{ target_ssh_keys_dir }}"
    state: directory
    mode: '0755'

- name: Create SSH key pair
  community.crypto.openssh_keypair:
    path: "{{ target_ssh_keys_dir }}/{{ ssh.key_name }}"
    size: "{{ ssh.size }}"

- name: Read public SSH key
  ansible.builtin.slurp:
    src: "{{ target_ssh_keys_dir }}/{{ ssh.key_name }}.pub"
  register: cloud_init_public_ssh_key
