distSpecVersion: "1.1.1"
storage:
  rootDirectory: "/var/lib/registry"
  retention:
    dryRun: false
    delay: "24h"
    policies:
      - repositories: ["**"]
        deleteUntagged: true
        deleteReferrers: true
        keepTags:
          - mostRecentlyPulledCount: 3
            mostRecentlyPushedCount: 3
      - keepTags:
          - patterns: [".*"]
http:
  address: "0.0.0.0"
  port: "5000"
  externalURL: "https://zot.innokentii-kozlov.com"
  compat: ["docker2s2"]
  auth:
    apikey: true
    openid:
      providers:
        oidc:
          credentialsFile: "/etc/zot/oidc-credentials.json"
          issuer: https://authentik.innokentii-kozlov.com/application/o/zot/
          keypath: ""
          scopes:
            - openid
            - profile
            - email
extensions:
  ui:
    enable: true
  search:
    enable: true
    cve:
      updateInterval: 24h
      trivy:
        dbRepository: ghcr.io/aquasecurity/trivy-db
  metrics:
    enable: true
    prometheus:
      path: "/metrics"
  sync:
    enable: true
    registries:
      - urls:
          - "https://quay.io"
        content:
          - prefix: "**"
            destination: "quay-images"
        onDemand: true
        tlsVerify: true
      - urls:
          - "https://ghcr.io"
        content:
          - prefix: "**"
            destination: "ghcr-images"
        onDemand: true
        tlsVerify: true
      - urls:
          - "https://gcr.io"
        content:
          - prefix: "**"
            destination: "gcr-images"
        onDemand: true
        tlsVerify: true
      - urls:
          - "https://data.forgejo.org"
        content:
          - prefix: "**"
            destination: "forgejo-images"
        onDemand: true
        tlsVerify: true
      - urls:
          - "https://codeberg.org"
        content:
          - prefix: "**"
            destination: "codeberg-images"
        onDemand: true
        tlsVerify: true
      - urls:
          - "https://registry-1.docker.io"
        content:
          - prefix: "**"
            destination: "docker-images"
        onDemand: true
        tlsVerify: true
