---
- name: Read secrets
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: read-secrets

- name: Generate secrets
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: generate-secrets

- name: Pull stack artifact
  hosts: ci-lab
  gather_facts: false
  roles:
    - role: pull-artifact

- name: Generate certificates
  hosts: ci-lab
  gather_facts: false
  roles:
    - role: generate-certs

- name: Render stack
  hosts: ci-lab
  gather_facts: false
  roles:
    - role: render-stack

- name: Deploy stack
  hosts: ci-lab
  gather_facts: false
  roles:
    - role: deploy-stack
