{
 "title": "Podman",
 "tags": [
  "podman",
  "containers",
  "quadlet"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "podman_exporter",
    "label": "exporter",
    "query": {
     "query": "label_values(podman_container_state, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(podman_container_state{job=~\"$podman_exporter\"})"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(podman_container_state{job=~\"$podman_exporter\"} == 2)"
    }
   ]
  },
  {
   "title": "Exited",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(podman_container_state{job=~\"$podman_exporter\"} == 5)"
    }
   ]
  },
  {
   "title": "Unhealthy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(podman_container_health{job=~\"$podman_exporter\"} == 1)"
    }
   ]
  },
  {
   "title": "Images",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(podman_image_info{job=~\"$podman_exporter\"})"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(podman_volume_info{job=~\"$podman_exporter\"})"
    }
   ]
  },
  {
   "title": "Networks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(podman_network_info{job=~\"$podman_exporter\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(podman_pod_state{job=~\"$podman_exporter\"})"
    }
   ]
  },
  {
   "title": "Total PIDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(podman_container_pids{job=~\"$podman_exporter\"})"
    }
   ]
  },
  {
   "title": "Image disk usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(podman_image_size{job=~\"$podman_exporter\"})"
    }
   ]
  },
  {
   "title": "RW layer size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(podman_container_rw_size_bytes{job=~\"$podman_exporter\"})"
    }
   ]
  },
  {
   "title": "Podman API version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "podman_system_api_version{job=~\"$podman_exporter\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Containers",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "podman_container_info{job=~\"$podman_exporter\"} * on(id) group_left() podman_container_state{job=~\"$podman_exporter\"}"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (name) (rate(podman_container_cpu_seconds_total{job=~\"$podman_exporter\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (podman_container_mem_usage_bytes{job=~\"$podman_exporter\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage (% of limit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (podman_container_mem_usage_bytes{job=~\"$podman_exporter\"}) / sum by (name) (podman_container_mem_limit_bytes{job=~\"$podman_exporter\"}) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(podman_container_net_input_total{job=~\"$podman_exporter\"}[$__rate_interval]))",
     "legendFormat": "{{name}} RX"
    },
    {
     "expr": "sum by (name) (rate(podman_container_net_output_total{job=~\"$podman_exporter\"}[$__rate_interval]))",
     "legendFormat": "{{name}} TX"
    }
   ]
  },
  {
   "title": "Block I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(podman_container_block_input_total{job=~\"$podman_exporter\"}[$__rate_interval]))",
     "legendFormat": "{{name}} read"
    },
    {
     "expr": "sum by (name) (rate(podman_container_block_output_total{job=~\"$podman_exporter\"}[$__rate_interval]))",
     "legendFormat": "{{name}} write"
    }
   ]
  },
  {
   "title": "PIDs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "sum by (name) (podman_container_pids{job=~\"$podman_exporter\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Volumes & Images", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Volumes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "podman_volume_info{job=~\"$podman_exporter\"}"
    }
   ]
  },
  {
   "title": "Images",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "podman_image_size{job=~\"$podman_exporter\"}"
    }
   ]
  },
  { "title": "Networks & Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Networks",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "podman_network_info{job=~\"$podman_exporter\"}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "podman_pod_info{job=~\"$podman_exporter\"} * on(id) group_left() podman_pod_state{job=~\"$podman_exporter\"}"
    }
   ]
  }
 ]
}