title: Home Lab
theme: dark
color: slate
language: en
target: _blank
statusStyle: "dot"
hideVersion: false
headerStyle: boxed

layout:
  Infrastructure:
    style: row
    columns: 4
    icon: mdi-server
  Monitoring:
    style: row
    columns: 4
    icon: mdi-chart-line
  Bookmarks:
    icon: mdi-bookmark

quicklaunch:
  searchDescriptions: true
  provider: google
