node: dell-optiplex-3000
stacks:
  - name: network
    description: Podman networks
    bundles:
      - name: zot.innokentii-kozlov.com/bundles/quadlets/network
        version: 0.0.0
        digest: sha256:6a7cdaccfeca77525d463daa683011112a31cb29a0257ad7bec5a2fbae62d73e
  - name: authentik
    description: Authentik IAM
    bundles:
      - name: zot.innokentii-kozlov.com/bundles/quadlets/authentik
        version: 0.0.0
        digest: sha256:aecf854baffe39ebe843424e92bd8bbe41bcb79e430857d8fb4c07f1b02aa02e
  - name: zot
    description: OCI registry
    bundles:
      - name: zot.innokentii-kozlov.com/bundles/quadlets/zot
        version: 0.0.0
        digest: sha256:431cce2e1c95df0605d21d2a42741e437f776c127784fa78b8fe55c7c26684f7
      - name: zot.innokentii-kozlov.com/bundles/configs/zot
        version: 0.0.0
        digest: sha256:73341c37c3f462c2ae376629e2efdb6f5672d7012b20c5704171042dc761c04c
  - name: blocky
    description: DNS
    bundles:
      - name: zot.innokentii-kozlov.com/bundles/quadlets/blocky
        version: 0.0.0
        digest: sha256:f5f87b49f181092020cf3ce9e5f18824a2b9dcbbf449788b0cc3e37e8c2507ae
      - name: zot.innokentii-kozlov.com/bundles/configs/blocky
        version: 0.0.0
        digest: sha256:db1cff803464ee0b4c99e001e023708fb3c41bdb85ffa735c3afdc8f4604d8c0
  - name: caddy
    description: Caddy reverse proxy
    bundles:
      - name: zot.innokentii-kozlov.com/bundles/quadlets/caddy
        version: 0.0.0
        digest: sha256:8513dd12dfeecda815134472ce53614715114445a688b0b1471cec00f3103059
      - name: zot.innokentii-kozlov.com/bundles/configs/caddy/dell-optiplex-3000
        version: 0.0.0
        digest: sha256:e04dd77fb4a1389e8d341d95900af442cc277c73aecb4128a4c49a230b8f93ff
  - name: grafana
    description: Grafana dashboards
    bundles:
      - name: zot.innokentii-kozlov.com/bundles/quadlets/grafana
        version: 0.0.0
        digest: sha256:d013e1f2ed119fbe85222c2350c03d8d341414e3c2ab1f49e54f9444185f1a54
      - name: zot.innokentii-kozlov.com/bundles/configs/grafana
        version: 0.0.0
        digest: sha256:ef46730b2d99cd0b539b0ada60eaca59b24ef69f6527d06e41b94db72c42c0b3
  - name: prometheus
    description: Prometheus metrics
    bundles:
      - name: zot.innokentii-kozlov.com/bundles/quadlets/prometheus
        version: 0.0.0
        digest: sha256:94b00291435ddef868b677ff86c611533c44c5c6495f1bcaee20ff9f0d911e2b
      - name: zot.innokentii-kozlov.com/bundles/configs/prometheus
        version: 0.0.0
        digest: sha256:a38b99b05c38a1a0f510af9c70bb21bfcd0bbd212aa5b1380ba3b2313519f24e
  - name: exporters
    description: Node and podman exporters
    bundles:
      - name: zot.innokentii-kozlov.com/bundles/quadlets/exporters
        version: 0.0.0
        digest: sha256:753f0f67f9f914d3493b96acfc7dc79ea6608e258bcdccea2b94198b8cb7cec2
  - name: forgejo
    description: Forgejo git hosting
    bundles:
      - name: zot.innokentii-kozlov.com/bundles/quadlets/forgejo
        version: 0.0.0
        digest: sha256:9ec2d730202d3137e5c4c91a8d70c0d361466a2e789ff920dd2a7d7370b7ad18
  - name: forgejo-runner
    description: Forgejo Actions runner
    bundles:
      - name: zot.innokentii-kozlov.com/bundles/quadlets/forgejo-runner
        version: 0.0.0
        digest: sha256:ab4b64e4f6901bdb2e04a5857db4e5750e9b873dd4fac2eabe13cc53b9e1123e
      - name: zot.innokentii-kozlov.com/bundles/configs/forgejo-runner/dell-optiplex-3000
        version: 0.0.0
        digest: sha256:f5380bb1b822d847e86e264b2130635fc08b4b0758686b026b7ad7f3372e9d31
