---
- name: Read scripts into variables
  ansible.builtin.set_fact:
    cloud_init_disk_setup_content: >
      {{ lookup('file', assets.scripts_dir ~ '/disk-setup.sh') }}
    cloud_init_firewall_setup_content: >
      {{ lookup('file', assets.scripts_dir ~ '/firewall-setup.sh') }}

- name: Generate user-data from template
  ansible.builtin.template:
    src: "{{ assets.templates_dir }}/user-data.j2"
    dest: "{{ cloud_init.work_dir }}/user-data"
    mode: '0644'
  vars:
    disk_setup_script: "{{ cloud_init_disk_setup_content }}"
    firewall_setup_script: "{{ cloud_init_firewall_setup_content }}"

- name: Generate meta-data from template
  ansible.builtin.template:
    src: "{{ assets.templates_dir }}/meta-data.j2"
    dest: "{{ cloud_init.work_dir }}/meta-data"
    mode: '0644'

- name: Generate network-config from template
  ansible.builtin.template:
    src: "{{ assets.templates_dir }}/network-config.j2"
    dest: "{{ cloud_init.work_dir }}/network-config"
    mode: '0644'
