SUBDIRS := \
	authentik \
	bazarr \
	blocky \
	caddy \
	exporters \
	forgejo \
	forgejo-runner \
	grafana \
	network \
	prometheus \
	prowlarr \
	radarr \
	sonarr \
	transmission \
	zot

include ../../common.mk
