---
workspace_dir: "/workspace"
target_dir: "/target"

secrets_path: "{{ workspace_dir }}/secrets.yaml"
target_generated_secrets_path: "{{ target_dir }}/generated-secrets.yaml"

artifact_tag: latest
artifact_ref: "zot.innokentii-kozlov.com/ci-lab-stack:{{ artifact_tag }}"

stack_dir: "/home/{{ ansible_user }}/stack"
certs_dir: "{{ stack_dir }}/certs"

postgres_cert_common_name: postgres
postgres_cert_country: FI
postgres_cert_organization: home-lab
postgres_cert_validity_days: 3650
