log:
  level: info
  job_level: info

runner:
  capacity: 2
  timeout: 3h
  fetch_interval: 2s
  labels:
    - docker:docker://zot.innokentii-kozlov.com/ghcr/catthehacker/ubuntu:act-latest
    - amd64:docker://zot.innokentii-kozlov.com/ghcr/catthehacker/ubuntu:act-latest
  envs:
    DOCKER_HOST: unix:///var/run/docker.sock
    CONTAINER_HOST: unix:///var/run/docker.sock

cache:
  enabled: true
  dir: /data/.cache

container:
  network: backend.network
  docker_host: unix:///run/user/1000/podman/podman.sock
  options: --security-opt label=type:container_runtime_t
  valid_volumes: []
  force_pull: false

host:
  workdir_parent: /var/tmp/act

server:
  connections:
    forgejo:
      url: https://forgejo.innokentii-kozlov.com/
      uuid: 65316132-3132-3334-6263-333331313431
      token_url: file:/run/secrets/forgejo-runner-connection-token
