node: raspberrypi-5
stacks:
  - name: network
    description: Podman networks
    bundles:
      - name: zot.innokentii-kozlov.com/bundles/quadlets/network
        version: 0.0.0
        digest: sha256:6a7cdaccfeca77525d463daa683011112a31cb29a0257ad7bec5a2fbae62d73e
  - name: exporters
    description: Node and podman exporters
    bundles:
      - name: zot.innokentii-kozlov.com/bundles/quadlets/exporters
        version: 0.0.0
        digest: sha256:753f0f67f9f914d3493b96acfc7dc79ea6608e258bcdccea2b94198b8cb7cec2
  - name: caddy
    description: Caddy reverse proxy
    bundles:
      - name: zot.innokentii-kozlov.com/bundles/quadlets/caddy
        version: 0.0.0
        digest: sha256:8513dd12dfeecda815134472ce53614715114445a688b0b1471cec00f3103059
      - name: zot.innokentii-kozlov.com/bundles/configs/caddy/raspberrypi-5
        version: 0.0.0
        digest: sha256:f986ed233b77d0cce4ed8201182f5cd9e25fb4917e36fd034a7b643f8964f374
  - name: forgejo-runner
    description: Forgejo Actions runner
    bundles:
      - name: zot.innokentii-kozlov.com/bundles/quadlets/forgejo-runner
        version: 0.0.0
        digest: sha256:ab4b64e4f6901bdb2e04a5857db4e5750e9b873dd4fac2eabe13cc53b9e1123e
      - name: zot.innokentii-kozlov.com/bundles/configs/forgejo-runner/raspberrypi-5
        version: 0.0.0
        digest: sha256:99d9b0961fe230efea53f719725b80b80c00737efed04be5f7bd552bd7b20344
