node: raspberrypi-5
stacks:
  - name: network
    description: Podman networks
    bundles:
      - name: zot.innokentii-kozlov.com/bundles/quadlets/network
        version: 0.0.0
        digest: sha256:50a3ce406c97e400fa4a00b5b25902c9cd5a696c00769ff138351911bf7bb92a
  - name: exporters
    description: Node and podman exporters
    bundles:
      - name: zot.innokentii-kozlov.com/bundles/quadlets/exporters
        version: 0.0.0
        digest: sha256:a103655932e9bc95976289a5a840ddd526987ab973b37c9050a9155af08a2e49
  - name: caddy
    description: Caddy reverse proxy
    bundles:
      - name: zot.innokentii-kozlov.com/bundles/quadlets/caddy
        version: 0.0.0
        digest: sha256:b4ba4d3ceb0b2cf5f26ea1f1815f6fdf6f6184edd307edf54d9efb0f270a2755
      - name: zot.innokentii-kozlov.com/bundles/configs/caddy/raspberrypi-5
        version: 0.0.0
        digest: sha256:fcb032bbc2c1c750d4f7e616b85da6da8f5cf6d9ae5504a51a3baa65b699c3a9
  - name: forgejo-runner
    description: Forgejo Actions runner
    bundles:
      - name: zot.innokentii-kozlov.com/bundles/quadlets/forgejo-runner
        version: 0.0.0
        digest: sha256:34077d314d262df2542e72bcf764e6b423913b16c967c854ef6183b0129b396d
      - name: zot.innokentii-kozlov.com/bundles/configs/forgejo-runner/raspberrypi-5
        version: 0.0.0
        digest: sha256:206ad443b8a783c19706715667e6fff8181262551d18fcba8052fe0a3514f1f4
