---
- name: Download Raspberry Pi OS image archive
  ansible.builtin.get_url:
    url: "{{ rpi_os.download_url | replace(' ', '') }}"
    dest: "{{ downloads_dir }}/{{ rpi_os.image_compressed | replace(' ', '') }}"
    mode: '0644'

- name: Decompress Raspberry Pi OS image archive
  ansible.builtin.shell: >
    unxz -k {{ downloads_dir }}/{{ rpi_os.image_compressed | replace(' ', '') }}
  args:
    creates: "{{ downloads_dir }}/{{ rpi_os.image | replace(' ', '') }}"
