site_name: Innokentii Kozlov - Home Lab

docs_dir: Documentation

repo_url: https://github.com/Kesha123/home-lab

plugins:
  - search
  - awesome-nav
  - section-index
  - minify:
      minify_html: true

theme:
  name: material
