{
 "title": "Zot",
 "description": "github.com/project-zot/zot v2.0.1",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "http_method",
    "query": {
     "query": "label_values(zot_http_method_latency_seconds_bucket,method)"
    }
   },
   {
    "name": "scheduler_workers_tasks_duration",
    "query": {
     "query": "label_values(zot_scheduler_workers_tasks_duration_seconds_bucket,name)"
    }
   },
   {
    "name": "storageName",
    "query": {
     "query": "label_values(zot_storage_lock_latency_seconds_bucket,storageName)"
    }
   },
   {
    "name": "repo_prefix",
    "query": {
     "query": "label_values(zot_repo_downloads_total,repo)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Downloads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "targets": [
    { "expr": "sum(zot_repo_downloads_total)", "legendFormat": "total" }
   ]
  },
  {
   "title": "Uploads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "targets": [
    { "expr": "sum(zot_repo_uploads_total)", "legendFormat": "total" }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "sum(zot_repo_storage_bytes)", "legendFormat": "total" }
   ]
  },
  {
   "title": "Downloads rate",
   "type": "timeseries",
   "description": "downloads/minute",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(zot_repo_downloads_total[1m]))*60",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Uploads rate",
   "type": "timeseries",
   "description": "uploads per minute",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(zot_repo_uploads_total[1m]))*60",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Storage Usage change",
   "type": "timeseries",
   "description": "change per minute",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(zot_repo_storage_bytes[1m]))*60",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Downloads by repo",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(zot_repo_downloads_total) by (repo)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uploads by repo",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum(zot_repo_uploads_total) by (repo)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Usage by repo",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(zot_repo_storage_bytes) by (repo)",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Downloads rate by repo",
   "type": "timeseries",
   "description": "downloads per minute",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(zot_repo_downloads_total[1m])) by (repo) *60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uploads rate by repo",
   "type": "timeseries",
   "description": "uploads per minute",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(zot_repo_uploads_total[1m])) by (repo) *60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Usage rate by repo",
   "type": "timeseries",
   "description": "change per minute",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(zot_repo_storage_bytes[1m])) by (repo) *60",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  { "title": "HTTP Repo latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "HTTP repo latency rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(zot_http_repo_latency_seconds_sum[1m]))*60",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "HTTP repo latency rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(zot_http_repo_latency_seconds_sum[$__rate_interval])",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  { "title": "Uploads by prefix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Uploads by repo prefix $repo_prefix",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 3.4285714285714284, "x": 0, "y": 53 },
   "repeat": "repo_prefix",
   "targets": [
    {
     "expr": "sum(zot_repo_uploads_total{repo=~\"$repo_prefix.*\"})",
     "legendFormat": "$repo_prefix"
    }
   ]
  },
  { "title": "Uploads rate by prefix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Uploads rate by repo prefix $repo_prefix",
   "type": "timeseries",
   "description": "rate per minute",
   "gridPos": { "h": 9, "w": 3.4285714285714284, "x": 0, "y": 63 },
   "repeat": "repo_prefix",
   "targets": [
    {
     "expr": "sum(rate(zot_repo_uploads_total{repo=~\"$repo_prefix.*\"}[1m]))*60",
     "legendFormat": "$repo_prefix"
    }
   ]
  },
  { "title": "Downloads by repo prefix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Downloads by repo prefix $repo_prefix",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3.4285714285714284, "x": 0, "y": 73 },
   "repeat": "repo_prefix",
   "targets": [
    {
     "expr": "sum(zot_repo_downloads_total{repo=~\"$repo_prefix.*\"})",
     "legendFormat": "$repo_prefix"
    }
   ]
  },
  { "title": "Downloads rate by prefix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Downloads rate by repo prefix $repo_prefix",
   "type": "timeseries",
   "description": "rate per minute",
   "gridPos": { "h": 8, "w": 3.4285714285714284, "x": 0, "y": 82 },
   "repeat": "repo_prefix",
   "targets": [
    {
     "expr": "sum(rate(zot_repo_downloads_total{repo=~\"$repo_prefix.*\"}[1m]))*60",
     "legendFormat": "$repo_prefix"
    }
   ]
  },
  { "title": "Storage per prefix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Storage Usage by repo prefix $repo_prefix",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 3.4285714285714284, "x": 0, "y": 91 },
   "repeat": "repo_prefix",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(zot_repo_storage_bytes{repo=~\"$repo_prefix.*\"})",
     "legendFormat": "$repo_prefix"
    }
   ]
  },
  { "title": "Storage rate per prefix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Storage Usage rate change by repo prefix $repo_prefix",
   "type": "timeseries",
   "description": "rate change per minute",
   "gridPos": { "h": 9, "w": 3.4285714285714284, "x": 0, "y": 101 },
   "repeat": "repo_prefix",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(zot_repo_storage_bytes{repo=~\"$repo_prefix.*\"}[1m]))*60",
     "legendFormat": "$repo_prefix"
    }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Generators - Priority High",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(zot_scheduler_generators_status{priority=\"high\"}) by (state)",
     "legendFormat": "{{priority}} {{state}}"
    }
   ]
  },
  {
   "title": "Generators - Priority Medium",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(zot_scheduler_generators_status{priority=\"medium\"}) by (state)",
     "legendFormat": "{{priority}} {{state}}"
    }
   ]
  },
  {
   "title": "Generators - Priority Low",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(zot_scheduler_generators_status{priority=\"low\"}) by (state)",
     "legendFormat": "{{priority}} {{state}}"
    }
   ]
  },
  { "title": "Schedule Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "Task Queue Length by priority",
   "type": "timeseries",
   "description": "Number of tasks in the queue waiting to be processed by scheduler workers",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(zot_scheduler_tasksqueue_length) by (priority)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total workers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "zot_scheduler_workers_total", "legendFormat": "total" }
   ]
  },
  {
   "title": "Workers by state",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(zot_scheduler_workers) by (state)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP Method Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 } },
  {
   "title": "$http_method",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "repeat": "http_method",
   "targets": [
    {
     "expr": "sum(increase(zot_http_method_latency_seconds_bucket{method=\"$http_method\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Heatmaps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 } },
  {
   "title": "$scheduler_workers_tasks_duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 140 },
   "repeat": "scheduler_workers_tasks_duration",
   "targets": [
    {
     "expr": "sum(increase(zot_scheduler_workers_tasks_duration_seconds_bucket{name=\"$scheduler_workers_tasks_duration\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage lock latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 } },
  {
   "title": "$storageName",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 150 },
   "repeat": "storageName",
   "targets": [
    {
     "expr": "sum(increase(zot_storage_lock_latency_seconds_bucket{storageName=\"$storageName\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}