---
- name: Prepare working directory for cloud-init files
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create working directory
      ansible.builtin.file:
        path: "{{ cloud_init.work_dir }}"
        state: directory
        mode: "0755"

- name: Generate SSH key pair for cloud-init
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create SSH key pair
      community.crypto.openssh_keypair:
        path: "{{ cloud_init.work_dir }}/id_rsa"
        size: 4096

    - name: Read public SSH key
      ansible.builtin.slurp:
        src: "{{ cloud_init.work_dir }}/id_rsa.pub"
      register: public_ssh_key

- name: Create cloud-init files
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Generate user-data from template
      ansible.builtin.template:
        src: /playbooks/templates/user-data.j2
        dest: "{{ cloud_init.work_dir }}/user-data"
        mode: "0644"

    - name: Generate meta-data from template
      ansible.builtin.template:
        src: /playbooks/templates/meta-data.j2
        dest: "{{ cloud_init.work_dir }}/meta-data"
        mode: "0644"

    - name: Generate network-config from template
      ansible.builtin.template:
        src: /playbooks/templates/network-config.j2
        dest: "{{ cloud_init.work_dir }}/network-config"
        mode: "0644"

- name: Inject cloud-init files into Raspberry Pi OS image
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Decompress Raspberry Pi OS image
      ansible.builtin.shell: >
        unxz -k /workspace/{{ rpi_os.image_compressed }}
      args:
        creates: /workspace/{{ rpi_os.image }}

    - name: Copy files into the FAT32 boot partition (Partition 1)
      ansible.builtin.shell: |
        START_SECTOR=$(sfdisk -l /workspace/{{ rpi_os.image }} | grep "W95 FAT32" | awk '{print $2}')
        OFFSET_BYTES=$((START_SECTOR * 512))
        export MTOOLS_SKIP_CHECK=1
        mcopy -o -i /workspace/{{ rpi_os.image }}@@${OFFSET_BYTES} {{ cloud_init.work_dir }}/user-data ::user-data
        mcopy -o -i /workspace/{{ rpi_os.image }}@@${OFFSET_BYTES} {{ cloud_init.work_dir }}/meta-data ::meta-data
        mcopy -o -i /workspace/{{ rpi_os.image }}@@${OFFSET_BYTES} {{ cloud_init.work_dir }}/network-config ::network-config
      args:
        executable: /bin/sh
