---
- name: Import kube cluster playbook
  ansible.builtin.import_playbook: k3s-ansible/playbooks/site.yml

- name: Export kubeconfig
  hosts: server
  gather_facts: false
  become: true
  tasks:
    - name: Download kubeconfig
      ansible.builtin.fetch:
        src: "{{ kubeconfig_path }}"
        dest: "{{ kubeconfig_path }}"
        flat: true
