[[registry]]
location = "docker.io"

[[registry.mirror]]
location = "zot.innokentii-kozlov.com/docker"

[[registry]]
location = "ghcr.io"

[[registry.mirror]]
location = "zot.innokentii-kozlov.com/ghcr"

[[registry]]
location = "quay.io"

[[registry.mirror]]
location = "zot.innokentii-kozlov.com/quay"

[[registry]]
location = "gcr.io"

[[registry.mirror]]
location = "zot.innokentii-kozlov.com/gcr"

[[registry]]
location = "data.forgejo.org"

[[registry.mirror]]
location = "zot.innokentii-kozlov.com/forgejo"

[[registry]]
location = "codeberg.org"

[[registry.mirror]]
location = "zot.innokentii-kozlov.com/codeberg"
