---
name: Wrapper Workflow K3S Install

on:
  pull_request:
    paths:
      - workflows/k3s-install/**
      - Makefile
      - Makefile-workflow.mk
      - .ansible-lint
      - .yamllint.yaml
      - .github/workflows/reusable-build-workflow.yml
      - .github/workflows/wrapper-workflow-k3s-install.yml
  workflow_dispatch:
    inputs:
      build_tag:
        description: Build tag for the workflow package
        required: false
        type: string
        default: ''
  workflow_call:
    inputs:
      build_tag:
        description: Build tag for the workflow package
        required: false
        type: string
        default: ''

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-workflow:
    uses: ./.github/workflows/reusable-build-workflow.yml
    with:
      workflow_name: k3s-install
      build_tag: ${{ inputs.build_tag != '' && inputs.build_tag || github.sha }}
