---
name: Wrapper Workflow RPI OS Setup

on:
  pull_request:
    paths:
      - workflows/rpi-os-setup/**
      - Makefile
      - Makefile-workflow.mk
      - .ansible-lint
      - .yamllint.yaml
      - .github/workflows/reusable-build-workflow.yml
      - .github/workflows/wrapper-workflow-rpi-os-setup.yml
  workflow_dispatch:
    inputs:
      build_tag:
        description: Build tag for the workflow package
        required: false
        type: string
        default: ''
  workflow_call:
    inputs:
      build_tag:
        description: Build tag for the workflow package
        required: false
        type: string
        default: ''

jobs:
  build-workflow:
    uses: ./.github/workflows/reusable-build-workflow.yml
    with:
      workflow_name: rpi-os-setup
      build_tag: ${{ inputs.build_tag != '' && inputs.build_tag || github.sha }}
